//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prorrogas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioGrupo
    {
        public long IdGrupoAperturado { get; set; }
        public short Numero { get; set; }
        public short IdAula { get; set; }
        public short IdDia { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual GrupoAperturado GrupoAperturado { get; set; }
    }
}
