//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prorrogas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prorroga
    {
        public int id { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int idEstudiante { get; set; }
        public int idCarrera { get; set; }
        public int idGrupo { get; set; }
        public int idModulo { get; set; }
        public int idUsuario { get; set; }
        public int idTipoProrroga { get; set; }
        public int idEstado { get; set; }
        public Nullable<System.DateTime> fechaExtension { get; set; }
    
        public virtual EstadoProrroga EstadoProrroga { get; set; }
        public virtual TipoProrroga TipoProrroga { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
